version: 2
jobs:
  build:
    docker:
      - image: vertispan/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - run:
          name: Initialize Bazel
          command: |
            # limit the bazel jobs due to failures in circleci
            echo "build --jobs=1" >> .bazelrc
            echo "build --local_ram_resources=512" >> .bazelrc
            echo "--host_jvm_args=-Xmx512m" >> .bazelrc
            bazel sync
      - run:
          name: Run bazel build to produce jsinterop classes, copy to maven project
          command: ./build.sh
      - run:
          name: Build maven jars and deploy
          command: |
            cd maven
            mvn deploy -Prelease -Dgpg.skip=true -Dossrh.username=$SONATYPE_USERNAME -Dossrh.password=$SONATYPE_APIKEY
      - run:
          name: Re-deploy to Vertispan repo
          command: |
            cd maven
            mvn deploy -Prelease -Dgpg.skip=true -DaltSnapshotDeploymentRepository=vertispan-snapshots::default::https://repo.vertispan.com/gwt-snapshot/ -Dartifactory.username=$ARTIFACTORY_USER -Dartifactory.password=$ARTIFACTORY_APIKEY


