version: 2
jobs:
  build: # builds the project with bazel and copies the source so maven can handle it
    docker:
      - image: vertispan/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restoring cache - bazel repository
          keys:
            - v2-bazel-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "build_defs/repository.bzl" }}
            - v2-bazel-{{ checksum ".bazelversion" }}-
            - v1-bazel-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "build_defs/repository.bzl" }}
          paths:
            - ~/bazel_repository_cache
            - ~/bazel_disk_cache
      - run:
          name: Initialize Bazel
          command: |
            # limit the bazel jobs due to failures in circleci
            echo "build --jobs=1" >> .bazelrc
            echo "build --local_ram_resources=512" >> .bazelrc
            echo "--host_jvm_args=-Xmx512m" >> .bazelrc
            # ask bazel to put its downloaded resources in a directory we can cache
            echo "build --repository_cache=~/bazel_repository_cache" >> .bazelrc
            # ask bazel to put build artifacts somewhere we can easily cache them
            echo "build --disk_cache=~/bazel_disk_cache" >> .bazelrc
            # download dependencies, ensure nothing is stale
            bazel sync
      - run:
          name: Run bazel build to produce jsinterop classes, copy to maven project
          command: ATTEMPTS=5 ./build.sh
      - persist_to_workspace:
          root: ~/project
          paths: maven/src
      - save_cache:
          name: Save Cache - bazel repository
          key: v2-bazel-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "build_defs/repository.bzl" }}
          paths:
            - ~/bazel_repository_cache
            - ~/bazel_disk_cache
  deploy-to-sonatype:
    docker:
      - image: vertispan/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name:  Restoring Cache - m2 repository
          keys:
            - v1-dependencies-{{ checksum "maven/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build maven jars and deploy
          command: |
            cd maven
            mvn deploy -Prelease -Dgpg.skip=true \
            -s ../.circleci/settings.xml -Dossrh.username=$SONATYPE_USERNAME -Dossrh.password=$SONATYPE_APIKEY
      - save_cache:
          name:  Save Cache - m2 repository
          paths:
            - ~/.m2/repository
          key: v1-dependencies-{{ checksum "maven/pom.xml" }}
  deploy-to-vertispan-artifactory:
    docker:
      - image: vertispan/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name:  Restoring Cache - m2 repository
          keys:
            - v1-dependencies-{{ checksum "maven/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Deploy to Vertispan repo
          command: |
            cd maven
            mvn deploy -Prelease -Dgpg.skip=true \
            -DaltSnapshotDeploymentRepository=vertispan-snapshots::https://repo.vertispan.com/gwt-snapshot/ \
            -s ../.circleci/settings.xml -Dartifactory.username=$ARTIFACTORY_USER -Dartifactory.password=$ARTIFACTORY_APIKEY
      - save_cache:
          name:  Save Cache - m2 repository
          paths:
            - ~/.m2/repository
          key: v1-dependencies-{{ checksum "maven/pom.xml" }}

workflows:
  version: 2
  ci_build:
    jobs:
      - build
      - deploy-to-sonatype:
          requires:
            - build
          context: deploy-keys
      - deploy-to-vertispan-artifactory:
          requires:
            - build
          context: deploy-keys